import Head from "next/head";
import { useSelector, useDispatch } from "react-redux";
import { selectUsers, getUsers, selectStatus } from "../redux/slices/userSlice";
import { isEmpty } from "lodash";
import styles from "../styles/Home.module.css";

export default function Home() {
  const users = useSelector(selectUsers);
  const status = useSelector(selectStatus);
  const dispatch = useDispatch();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {isEmpty(users) ? (
          <p>Users not loaded!</p>
        ) : (
          <div className={styles.grid}>
            {users.map((user, index) => (
              <p className={styles.card} key={index}>
                {user.name}
              </p>
            ))}
          </div>
        )}

        <button
          className={styles.button}
          onClick={() => {
            dispatch(getUsers());
          }}
        >
          Load User Data
        </button>
        <span>status: {status}</span>
      </main>
    </div>
  );
}
